version: "3.9"

services:

  # app:
  #   image: django-react-prod_front
  #   build: 
  #     context: ./react-client
  #     dockerfile: Dockerfile.prod
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - api


  api:
    image: django-react-prod_back
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    entrypoint: ./entrypoint.sh
    volumes:
      - staticfiles:/home/api/web/staticfiles
      - mediafiles:/home/api/web/mediafiles
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - postgres_db
    

  postgres_db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db

  adminer:
    image: adminer
    ports:
      - 8080:8080

  
  nginx:
    image: django-react-prod_front
    build:
      context: ./react-client
      dockerfile: Dockerfile.prod
    volumes:
      - staticfiles:/staticfiles
      - mediafiles:/mediafiles
    ports:
      - "80:80"
    depends_on:
      - api


volumes:
  postgres-data:
  staticfiles:
  mediafiles:
